import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
df = sns.load_dataset('tips')
df = pd.DataFrame(df)
print(df)
sns.lineplot(data=df, x="size" , y="total_bill")
plt.show()
sns.barplot(data=df, x= "day", y="tip", ci=None)
plt.show()
sns.countplot(data=df, x="day")
plt.show()
sns.histplot(data=df, x="total_bill", bins=10, kde=True)
plt.show()
sns.boxplot(data=df, x="day", y="total_bill")
plt.show()
sns.violinplot(data=df, x="day", y="total_bill")
plt.show()
sns.scatterplot(data=df, x="total_bill", y="tip", hue="day")
plt.show()
sns.pairplot(df, hue="day")
plt.show() 
corrMat = df.select_dtypes(include=['number']).corr()
sns.heatmap(corrMat, annot=True, cmap='coolwarm')
plt.show()
